version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    networks:
      - cloudflare-tunnel
      - minecraft-networks
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      JVM_OPTS: "-XX:MaxRAMPercentage=75"
      DIFFICULTY: "hard"
      MOTD: CSSA Minecraft Server
      PAUSE_WHEN_EMPTY_SECONDS: 0
      MAX_TICK_TIME: -1
      
    volumes:
      - minecraft-data:/data
    deploy:
      placement:
        constraints:
          - node.hostname == ubuntu-docker-1
      resources:
        limits:
          cpus: "2.5"   
          memory: "8G"  
        reservations:
          cpus: "2" 
          memory: "6G" 
  minecraft-server-backups:
    image: itzg/mc-backup
    networks:
      - minecraft-networks
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: minecraft-server
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"     
      POST_BACKUP_SCRIPT: |
        echo "Backup done!"
      PRUNE_BACKUPS_DAYS: 5
    volumes:
      - minecraft-data:/data:ro
      - minecraft-backup:/backups
    deploy:
      placement:
        constraints:
          - node.hostname == ubuntu-docker-1
      resources:
        limits:
          memory: 2G
    
networks:
  cloudflare-tunnel:
    external: true
    name: cloudflare-tunnel
  minecraft-networks:
    name: minecraft-networks
  
volumes:
  minecraft-data:
    driver_opts:
      type: cifs
      o: username=${NAS_USERNAME},password=${NAS_PASSWORD},vers=3.0,cache=loose,actimeo=30,rsize=65536,wsize=65536
      device: //${NAS_IP}/mc/data
  minecraft-backup:
    driver_opts:
      type: cifs
      o: username=${NAS_USERNAME},password=${NAS_PASSWORD},vers=3.0,cache=loose,actimeo=30,rsize=65536,wsize=65536
      device: //${NAS_IP}/mc/backup
