version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: "minecraft-server"
    networks:
      - cloudflare-tunnel
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      JVM_OPTS: "-XX:MaxRAMPercentage=75"
      DIFFICULTY: "hard"
      MOTD: CSSA Minecraft Server
    volumes:
      - minecraft-data:/data

  minecraft-server-backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: minecraft-server
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"        
      PRUNE_BACKUPS_DAYS: 5
    volumes:
      - minecraft-data:/data:ro
      - minecraft-backup:/backups

networks:
  cloudflare-tunnel:
    external: true
    name: cloudflare-tunnel

volumes:
  minecraft-data:
    driver_opts:
      type: cifs
      o: username=${NAS_USERNAME},password=${NAS_PASSWORD},vers=3.0,dir_mode=0777,file_mode=0777
      device: //${NAS_IP}/mc/data
  minecraft-backup:
    driver_opts:
      type: cifs
      o: username=${NAS_USERNAME},password=${NAS_PASSWORD},vers=3.0,dir_mode=0777,file_mode=0777
      device: //${NAS_IP}/mc/backup
