version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    networks:
      - minecraft-networks
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
      JVM_OPTS: "-XX:MaxRAMPercentage=75"
      DIFFICULTY: "hard"
      MOTD: CSSA Minecraft Server
      PAUSE_WHEN_EMPTY_SECONDS: 0
      MAX_TICK_TIME: -1
      
    volumes:
      - minecraft-data:/data
  minecraft-server-backups:
    image: itzg/mc-backup
    networks:
      - minecraft-networks
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: minecraft-server
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"     
      POST_BACKUP_SCRIPT: |
        echo "Backup done!"
      PRUNE_BACKUPS_DAYS: 5
    volumes:
      - minecraft-data:/data:ro
      - minecraft-backup:/backups

networks:
  minecraft-networks:
    name: minecraft-networks

volumes:
  minecraft-data:
    driver: local
    driver_opts:
      type: none
      device: /home/cssa/minecraft_server/data
      o: bind
  minecraft-backup:
    driver: local
    driver_opts:
      type: none
      device: /home/cssa/minecraft_server/backup
      o: bind